### ISSUE TITLE
Assign tags modal window after scrolling down molecules moves across the screen

### ISSUE THREAD

**Issue by simonadachova** [m2ms/fragalysis-frontend#1151]
- click on edit tag pencil
- scroll down/up the Hit navigator
- modal window moves across all screen 

https://github.com/m2ms/fragalysis-frontend/assets/104004432/f9d942b1-ca5b-4775-a548-fbcc817f25cf

**Comment by boriskovar-m2ms** [comment]
There is a solution for this on the RHS where dialog for inspirations (the F button) hides after the component which is attached to scrolls out of the view/visible area.

**Comment by phraenquex** [comment]
@RoboMatuska I assume this bug is getting fixed in #1104 ?

**Comment by simonadachova** [comment]
Issue still occurs. 

https://github.com/m2ms/fragalysis-frontend/assets/104004432/55882b1c-8de5-49af-961d-9c51c8fb44ce

**Comment by phraenquex** [comment]
Made irrelevant by #1140 - now just a cosmetic issue, doesn't need fixing.

The specific fix would be:  if _any_ event occurs with the mouse outside the assign-tags window, then make the assign-tags window disappear.  It currently does it for any click;  it could do it for scroll-wheel actions too.  

But let's just leave it.
