### ISSUE TITLE
Example XCA v3 data inputs with altlocs

### ISSUE THREAD

**Issue by mwinokan** [m2ms/fragalysis-frontend#1962]
@tdudgeon needs some realistic altloc-containing fragalysis targets. @mwinokan to ask ASAP folk for an example

Else @phraenquex suggests manually adding an altloc to a ligand block in the PDB

**Comment by mwinokan** [comment]
In v2 altlocs appear combined into the same ligand SDF, it might be possible to just grep for `(2)` across the ligand SDFs to find a target with altlocs

Edit: the above does not work as the molecules have no properties stored in the SDF

**Comment by mwinokan** [comment]
@tdudgeon by running `grep -Roc "RDKit" */aligned_files/*/*_ligand.sdf | awk -F: '$2 >= 2 {print $1}'` in my downloads folder I got some results:

```
A71EV2A/aligned_files/A0515a/A0515a_ligand.sdf
A71EV2A/aligned_files/A1140a/A1140a_ligand.sdf
D68EV3C/aligned_files/7go1-b/7go1-b_ligand.sdf
D68EV3C/aligned_files/7goo-a/7goo-a_ligand.sdf
D68EV3C/aligned_files/7gp6-a/7gp6-a_ligand.sdf
D68EV3C/aligned_files/B0454a/B0454a_ligand.sdf
Flavi_NS5_RdRp (1)/aligned_files/d0153b/d0153b_ligand.sdf
Flavi_NS5_RdRp (1)/aligned_files/d0160c/d0160c_ligand.sdf
Flavi_NS5_RdRp (1)/aligned_files/d0249a/d0249a_ligand.sdf
SARS2_Nprot (5)/aligned_files/Nprot-frag-x0361a/Nprot-frag-x0361a_ligand.sdf
SARS2_Nprot (5)/aligned_files/Nprot-frag-x0392a/Nprot-frag-x0392a_ligand.sdf
SARS2_Nprot (5)/aligned_files/Nprot-x1299a/Nprot-x1299a_ligand.sdf
SARS2_Nprot (5)/aligned_files/Nprot-x1574a/Nprot-x1574a_ligand.sdf
SARS2_Nprot (5)/aligned_files/Nprot-x1651a/Nprot-x1651a_ligand.sdf
SARS2_Nprot (5)/aligned_files/Nprot-x1882a/Nprot-x1882a_ligand.sdf
```

**Comment by tdudgeon** [comment]
@ConorFWild @mwinokan I'm not seeing what I was expecting when encountering a real altloc.
An example for `A71EV2A-x1140`.

The PDB contains:
```
HETATM 1705  N  ALIG A 147      15.257  13.319  24.822  0.32 26.50           N
HETATM 1706  C  ALIG A 147      11.099  13.101  24.622  0.32 17.00           C
HETATM 1707  O  ALIG A 147      13.789  10.717  24.343  0.32 17.03           O
HETATM 1708  C1 ALIG A 147       9.723  13.149  24.759  0.32 15.95           C
HETATM 1709  C10ALIG A 147      16.121  13.592  26.981  0.32 28.45           C
HETATM 1710  C11ALIG A 147      14.824  13.580  26.201  0.32 28.13           C
HETATM 1711  C2 ALIG A 147       8.987  11.985  24.615  0.32 15.52           C
HETATM 1712  C3 ALIG A 147       9.621  10.802  24.315  0.32 14.92           C
HETATM 1713  C4 ALIG A 147      10.995  10.768  24.132  0.32 15.30           C
HETATM 1714  C5 ALIG A 147      11.764  11.923  24.292  0.32 16.71           C
HETATM 1715  C6 ALIG A 147      13.268  11.798  24.184  0.32 19.24           C
HETATM 1716  C7 ALIG A 147      14.153  13.008  23.891  0.32 23.03           C
HETATM 1717  C8 ALIG A 147      16.243  12.237  24.964  0.32 27.14           C
HETATM 1718  C9 ALIG A 147      16.986  12.576  26.256  0.32 27.21           C
HETATM 1719 CL  ALIG A 147      11.989  14.522  24.984  0.32 19.07          CL
HETATM 1720  N  BLIG A 147      14.721  13.885  24.522  0.32 28.46           N
HETATM 1721  C  BLIG A 147      10.571  11.120  23.989  0.32 20.48           C
HETATM 1722  O  BLIG A 147      13.505  11.306  24.082  0.32 19.48           O
HETATM 1723  C1 BLIG A 147       9.245  11.050  24.379  0.32 20.12           C
HETATM 1724  C10BLIG A 147      15.979  13.254  26.395  0.32 29.71           C
HETATM 1725  C11BLIG A 147      14.588  13.632  25.965  0.32 30.24           C
HETATM 1726  C2 BLIG A 147       8.642  12.161  24.942  0.32 19.97           C
HETATM 1727  C3 BLIG A 147       9.366  13.317  25.141  0.32 20.36           C
HETATM 1728  C4 BLIG A 147      10.711  13.364  24.820  0.32 20.27           C
HETATM 1729  C5 BLIG A 147      11.346  12.252  24.247  0.32 21.15           C
HETATM 1730  C6 BLIG A 147      12.822  12.313  24.022  0.32 23.08           C
HETATM 1731  C7 BLIG A 147      13.476  13.665  23.770  0.32 26.38           C
HETATM 1732  C8 BLIG A 147      15.832  13.018  24.090  0.32 28.73           C
HETATM 1733  C9 BLIG A 147      16.379  12.395  25.383  0.32 28.48           C
HETATM 1734 CL  BLIG A 147      11.159   9.855  22.960  0.32 23.50          CL
```

The `meta_aligner.yaml` contains this:
```
    aligned_files:
      A:
        '147':
          A: {}
          B:
            '1':
              A71EV2A-x0526+A+147+0+1: {structure: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1.pdb,
                artefacts: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_artefacts.pdb,
                sigmaa_map: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_sigmaa.ccp4,
                diff_map: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_diff.ccp4,
                sigmaa_map_crystallographic: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_sigmaa_crystallographic.ccp4,
                diff_map_crystallographic: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_diff_crystallographic.ccp4,
                event_map: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_event.ccp4,
                event_map_crystallographic: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_event_crystallographic.ccp4,
                pdb_apo: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_apo.pdb,
                pdb_apo_solv: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_apo-solv.pdb,
                pdb_apo_desolv: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_apo-desolv.pdb,
                ligand_mol: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_ligand.mol,
                ligand_sdf: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_ligand.sdf,
                ligand_pdb: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_ligand.pdb,
                ligand_smiles: upload_1/aligned_files/A71EV2A-x1140/A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_ligand.smi,
                ligand_name: LIG, ligand_smiles_string: O=C(CN1CCCC1)c1ccccc1Cl}
```
e.g. the A altloc seems to be missing.

The files look like this:
```
$ ls -l
total 8068
-rw-rw-r-- 1 timbo timbo    5279 Nov 25 14:51 A71EV2A-x1140_A_147_A_1_A71EV2A-x0526+A+147+0+1_artefacts.pdb
-rw-rw-r-- 1 timbo timbo  201024 Nov 25 14:51 A71EV2A-x1140_A_147_A_1_A71EV2A-x0526+A+147+0+1_diff.ccp4
-rw-rw-r-- 1 timbo timbo 1101336 Nov 25 14:51 A71EV2A-x1140_A_147_A_1_A71EV2A-x0526+A+147+0+1_diff_crystallographic.ccp4
-rw-rw-r-- 1 timbo timbo  201024 Nov 25 14:51 A71EV2A-x1140_A_147_A_1_A71EV2A-x0526+A+147+0+1_event.ccp4
-rw-rw-r-- 1 timbo timbo 1101336 Nov 25 14:51 A71EV2A-x1140_A_147_A_1_A71EV2A-x0526+A+147+0+1_event_crystallographic.ccp4
-rw-rw-r-- 1 timbo timbo   96161 Nov 25 14:51 A71EV2A-x1140_A_147_A_1_A71EV2A-x0526+A+147+0+1.pdb
-rw-rw-r-- 1 timbo timbo  201024 Nov 25 14:51 A71EV2A-x1140_A_147_A_1_A71EV2A-x0526+A+147+0+1_sigmaa.ccp4
-rw-rw-r-- 1 timbo timbo 1101336 Nov 25 14:51 A71EV2A-x1140_A_147_A_1_A71EV2A-x0526+A+147+0+1_sigmaa_crystallographic.ccp4
-rw-rw-r-- 1 timbo timbo   93083 Nov 25 14:54 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_apo-desolv.pdb
-rw-rw-r-- 1 timbo timbo   93650 Nov 25 14:54 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_apo.pdb
-rw-rw-r-- 1 timbo timbo     567 Nov 25 14:54 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_apo-solv.pdb
-rw-rw-r-- 1 timbo timbo    5279 Nov 25 14:51 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_artefacts.pdb
-rw-rw-r-- 1 timbo timbo  201024 Nov 25 14:51 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_diff.ccp4
-rw-rw-r-- 1 timbo timbo 1101336 Nov 25 14:51 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_diff_crystallographic.ccp4
-rw-rw-r-- 1 timbo timbo  201024 Nov 25 14:51 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_event.ccp4
-rw-rw-r-- 1 timbo timbo 1101336 Nov 25 14:51 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_event_crystallographic.ccp4
-rw-rw-r-- 1 timbo timbo    2639 Nov 25 14:54 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_ligand.mol
-rw-rw-r-- 1 timbo timbo    2430 Nov 25 14:54 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_ligand.pdb
-rw-rw-r-- 1 timbo timbo    2774 Nov 25 14:54 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_ligand.sdf
-rw-rw-r-- 1 timbo timbo      23 Nov 25 14:54 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_ligand.smi
-rw-rw-r-- 1 timbo timbo   96161 Nov 25 14:51 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1.pdb
-rw-rw-r-- 1 timbo timbo  201024 Nov 25 14:51 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_sigmaa.ccp4
-rw-rw-r-- 1 timbo timbo 1101336 Nov 25 14:51 A71EV2A-x1140_A_147_B_1_A71EV2A-x0526+A+147+0+1_sigmaa_crystallographic.ccp4
```
e.g. all seem to be there?

**Comment by tdudgeon** [comment]
Also, the aligned PDB file still contains both altlocs:
```
HETATM 1087  N  ALIG A 147      14.558  12.381  25.145  0.32 26.50           N  
HETATM 1088  C  ALIG A 147      10.411  12.294  24.732  0.32 17.00           C  
HETATM 1089  O  ALIG A 147      13.027   9.814  24.671  0.32 17.03           O  
HETATM 1090  C1 ALIG A 147       9.032  12.392  24.795  0.32 15.95           C  
HETATM 1091  C10ALIG A 147      15.318  12.696  27.337  0.32 28.45           C  
HETATM 1092  C11ALIG A 147      14.064  12.701  26.490  0.32 28.13           C  
HETATM 1093  C2 ALIG A 147       8.265  11.248  24.649  0.32 15.52           C  
HETATM 1094  C3 ALIG A 147       8.872  10.036  24.420  0.32 14.92           C  
HETATM 1095  C4 ALIG A 147      10.251   9.950  24.311  0.32 15.30           C  
HETATM 1096  C5 ALIG A 147      11.051  11.084  24.475  0.32 16.71           C  
HETATM 1097  C6 ALIG A 147      12.553  10.906  24.451  0.32 19.24           C  
HETATM 1098  C7 ALIG A 147      13.494  12.075  24.167  0.32 23.03           C  
HETATM 1099  C8 ALIG A 147      15.497  11.272  25.373  0.32 27.14           C  
HETATM 1100  C9 ALIG A 147      16.184  11.629  26.691  0.32 27.21           C  
HETATM 1101 CL  ALIG A 147      11.330  13.696  25.096  0.32 19.07          CL  
HETATM 1102  N  BLIG A 147      14.058  12.954  24.799  0.32 28.46           N  
HETATM 1103  C  BLIG A 147       9.848  10.311  24.135  0.32 20.48           C  
HETATM 1104  O  BLIG A 147      12.778  10.403  24.377  0.32 19.48           O  
HETATM 1105  C1 BLIG A 147       8.502  10.298  24.457  0.32 20.12           C  
HETATM 1106  C10BLIG A 147      15.195  12.344  26.755  0.32 29.71           C  
HETATM 1107  C11BLIG A 147      13.842  12.753  26.240  0.32 30.24           C  
HETATM 1108  C2 BLIG A 147       7.910  11.446  24.952  0.32 19.97           C  
HETATM 1109  C3 BLIG A 147       8.662  12.584  25.152  0.32 20.36           C  
HETATM 1110  C4 BLIG A 147      10.023  12.576  24.901  0.32 20.27           C  
HETATM 1111  C5 BLIG A 147      10.647  11.425  24.398  0.32 21.15           C  
HETATM 1112  C6 BLIG A 147      12.134  11.430  24.249  0.32 23.08           C  
HETATM 1113  C7 BLIG A 147      12.847  12.750  23.990  0.32 26.38           C  
HETATM 1114  C8 BLIG A 147      15.159  12.037  24.454  0.32 28.73           C  
HETATM 1115  C9 BLIG A 147      15.617  11.439  25.793  0.32 28.48           C  
HETATM 1116 CL  BLIG A 147      10.444   8.994  23.179  0.32 23.50          CL
```

**Comment by mwinokan** [comment]
Thanks for confirming the aligned PDB behaviour @tdudgeon 

@ConorFWild could you please make sure only the single relevant altloc is written?

**Comment by mwinokan** [comment]
@tdudgeon says that if it is just standard `gemmi` code then potentially he can do it if pointed in the right direction

**Comment by mwinokan** [comment]
@ConorFWild says this is an easy fix

**Comment by mwinokan** [comment]
@tdudgeon Conor says he has fixed this on the [20251023](https://github.com/xchem/xchem-align/tree/20251023) branch. Could you try regenerating the test data with the latest code please?

**Comment by tdudgeon** [comment]
@mwinokan @ConorFWild 
The files are now better (each altloc observation now has only the single, correct altloc present), but the altloc letter is still present, even though it is now not an altoloc. e.g. the LIG section of the PDB looks like this:
```
HETATM 1098  N  ALIG A 201       5.450  10.239  26.602  0.36 23.03           N  
HETATM 1099  C  ALIG A 201       9.993  11.982  23.113  0.36 28.58           C  
HETATM 1100  O  ALIG A 201       9.625  11.851  24.507  0.36 27.19           O  
HETATM 1101  C1 ALIG A 201       8.596  12.588  24.916  0.36 26.12           C  
HETATM 1102  C2 ALIG A 201       7.491  11.761  25.467  0.36 24.46           C  
HETATM 1103  C3 ALIG A 201       6.577  12.343  26.343  0.36 23.76           C  
HETATM 1104  C4 ALIG A 201       5.591  11.538  26.881  0.36 23.60           C  
HETATM 1105  C5 ALIG A 201       6.318   9.695  25.748  0.36 23.24           C  
HETATM 1106  C6 ALIG A 201       7.355  10.387  25.158  0.36 23.73           C  
HETATM 1107  N1 ALIG A 201       8.228   9.709  24.321  0.36 23.02           N  
HETATM 1108  O1 ALIG A 201       8.578  13.793  24.886  0.36 26.27           O
```
This is not really impacting the ligand file generation as only a single molecule (SDF or MOL) is generated. 


But the other problem still remains. The YAML output still looks like this:
```
    aligned_files:
      A:
        '201':
          A: {}
          B:
            '1':
              A71EV2A-x0526+A+147+0+1: {structure: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1.pdb,
                artefacts: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_artefacts.pdb,
                sigmaa_map: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_sigmaa.ccp4,
                diff_map: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_diff.ccp4,
                sigmaa_map_crystallographic: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_sigmaa_crystallographic.ccp4,
                diff_map_crystallographic: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_diff_crystallographic.ccp4,
                event_map: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_event.ccp4,
                event_map_crystallographic: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_event_crystallographic.ccp4,
                pdb_apo: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_apo.pdb,
                pdb_apo_solv: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_apo-solv.pdb,
                pdb_apo_desolv: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_apo-desolv.pdb,
                ligand_mol: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_ligand.mol,
                ligand_sdf: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_ligand.sdf,
                ligand_pdb: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_ligand.pdb,
                ligand_smiles: upload_1/aligned_files/A71EV2A-x0515/A71EV2A-x0515_A_201_B_1_A71EV2A-x0526+A+147+0+1_ligand.smi,
                ligand_name: LIG, ligand_smiles_string: COC(=O)c1ccncc1N}
```
Note the data for altloc A is still missing.

**Comment by tdudgeon** [comment]
Also, the backslash character is still present in lots of places towards  the bottom of the YAML output. e.g.
```
conformer_sites:
  A71EV2A-x0202+A+201+0+1:
    members: ["A71EV2A-x0202/A/201/\0/1"]
    reference_ligand_id: "A71EV2A-x0202/A/201/\0/1"
```

**Comment by ConorFWild** [comment]
@tdudgeon @mwinokan 

The presence of the altloc character is very much intended - otherwise we destroy the link to the original data in the PDB file which seems unwise

Most recent push should fix the issue with null characters!

**Comment by mwinokan** [comment]
@tdudgeon has received @ConorFWild's latest changes:

- the backslash null altlocs (`\0`) appear to be fixed
- aligned PDBs now only contain one altloc (with the altloc letter still present)

Tim says that **the YAML output is still incorrect**, but now B altloc is before the empty A altloc

@mwinokan will ping @ConorFWild

**Comment by tdudgeon** [comment]
Data in YAML output now looks like this:
```
    aligned_files:
      A:
        '201':
          B: {}
          A:
            '1':
              A71EV2A-x0526+A+147+0+1: {structure: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1.pdb,
                artefacts: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_artefacts.pdb,
                sigmaa_map: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_sigmaa.ccp4,
                diff_map: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_diff.ccp4,
                sigmaa_map_crystallographic: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_sigmaa_crystallographic.ccp4,
                diff_map_crystallographic: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_diff_crystallographic.ccp4,
                event_map: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_event.ccp4,
                event_map_crystallographic: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_event_crystallographic.ccp4,
                pdb_apo: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_apo.pdb,
                pdb_apo_solv: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_apo-solv.pdb,
                pdb_apo_desolv: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_apo-desolv.pdb,
                ligand_mol: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_ligand.mol,
                ligand_sdf: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_ligand.sdf,
                ligand_pdb: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_ligand.pdb,
                ligand_smiles: upload_1/aligned_files/A71EV2A-x3522/A71EV2A-x3522_A_201_A_1_A71EV2A-x0526+A+147+0+1_ligand.smi,
                ligand_name: LIG, ligand_smiles_string: COCC(=O)Nc1c(Cl)cc(C)cc1OCc1ncccn1}
```

**Comment by ConorFWild** [comment]
@tdudgeon @mwinokan 
Fixed in most recent push!
