### ISSUE TITLE
Selected compounds tab

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#265]
- [x] This tab is visible at all times.

- [x] The compound shall be displayed in the same manner as are displayed molecules in the Hit navigator with additions documented in following issues:

#272 #273 #274 

- [x] There should be no header for scores. For each compound the scores are displayed in the component (in general there can be displayed from 0 up to 7 scores different scores for each custom dataset) and their names are displayed only in the tool tip.

![image](https://user-images.githubusercontent.com/16878338/79873524-82997300-83e7-11ea-8695-806dbc637f48.png)

**Comment by tibor-postek-m2ms** [comment]
- [ ] Load new pdf file and merge BE branch 
@Waztom @reskyner I'm not able to build app after merging your changes
![image](https://user-images.githubusercontent.com/57392303/84009942-46f54100-a974-11ea-80b6-e8652c4e2d7d.png)

**Comment by tibor-postek-m2ms** [comment]
@reskyner @Waztom During upload .sdf file to local machine environment was displayed following error
![image](https://user-images.githubusercontent.com/57392303/84047443-90ad4e00-a9ab-11ea-959c-e3d4bcbe6c49.png)

**Comment by tibor-postek-m2ms** [comment]
> @reskyner @Waztom During upload .sdf file to local machine environment was displayed following error
> ![image](https://user-images.githubusercontent.com/57392303/84047443-90ad4e00-a9ab-11ea-959c-e3d4bcbe6c49.png)

This one is fixed by creating following directory `mkdir -p data/media/compound_sets`

**Comment by Waztom** [comment]
@tibor-postek-m2ms apologies I forgot to mention that the folder 'compound_sets' needs to be created manually - we still need to update the code to create the directory. I am back online today and please ping me if you need any help with tracebacks etc.

**Comment by postektibor** [comment]
> @tibor-postek-m2ms apologies I forgot to mention that the folder 'compound_sets' needs to be created manually - we still need to update the code to create the directory. I am back online today and please ping me if you need any help with tracebacks etc.
> 
> Have added issue - [xchem/fragalysis-backend#166](https://github.com/xchem/fragalysis-backend/issues/166)

yes, but it doesnt solve trouble with loader...
`Protein created = False OLD MOLS = 1 <rdkit.Chem.rdchem.Mol object at 0x7f572b445830> Skipping contacts - Mpro-x1425_0 Skipping confidence - Mpro-x1425_0 Mpro-x1458_0 Path - /code/media/NEW_DATA/Mpro/Mpro-x1458_0/Mpro-x1458_0_pandda.map not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1458_0/Mpro-x1458_0.mtz not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1458_0/Mpro-x1458_0_contacts.json not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1458_0/Mpro-x1458_0_lig_conf.json not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1458_0/Mpro-x1458_0_acceptor.ccp4 not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1458_0/Mpro-x1458_0_donor.ccp4 not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1458_0/Mpro-x1458_0_apolar.ccp4 not found. Protein created = False OLD MOLS = 1 <rdkit.Chem.rdchem.Mol object at 0x7f572b445830> Skipping contacts - Mpro-x1458_0 Skipping confidence - Mpro-x1458_0 Mpro-x1478_0 Path - /code/media/NEW_DATA/Mpro/Mpro-x1478_0/Mpro-x1478_0_pandda.map not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1478_0/Mpro-x1478_0.mtz not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1478_0/Mpro-x1478_0_contacts.json not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1478_0/Mpro-x1478_0_lig_conf.json not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1478_0/Mpro-x1478_0_acceptor.ccp4 not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1478_0/Mpro-x1478_0_donor.ccp4 not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1478_0/Mpro-x1478_0_apolar.ccp4 not found. Protein created = False OLD MOLS = 1 <rdkit.Chem.rdchem.Mol object at 0x7f572b445830> Skipping contacts - Mpro-x1478_0 Skipping confidence - Mpro-x1478_0 Mpro-x1493_0 Path - /code/media/NEW_DATA/Mpro/Mpro-x1493_0/Mpro-x1493_0_pandda.map not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1493_0/Mpro-x1493_0.mtz not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1493_0/Mpro-x1493_0_contacts.json not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1493_0/Mpro-x1493_0_lig_conf.json not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1493_0/Mpro-x1493_0_acceptor.ccp4 not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1493_0/Mpro-x1493_0_donor.ccp4 not found. Path - /code/media/NEW_DATA/Mpro/Mpro-x1493_0/Mpro-x1493_0_apolar.ccp4 not found. Protein created = False OLD MOLS = 1 <rdkit.Chem.rdchem.Mol object at 0x7f572b445830> Skipping contacts - Mpro-x1493_0 Skipping confidence - Mpro-x1493_0 Analysing target: Mpro Analysing 96 molecules for Mpro Traceback (most recent call last): File "loader.py", line 43, in <module> process_target(prefix, target_name, app=app) File "/code/loader/loaders.py", line 988, in process_target analyse_target(target_name, target_path) File "/code/loader/loaders.py", line 801, in analyse_target number = row['id'] File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line 868, in __getitem__ result = self.index.get_value(self, key) File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexes/base.py", line 4389, in get_value raise e1 KeyError: 'id' Sentry is attempting to send 1 pending error messages Waiting up to 2.0 seconds Press Ctrl-C to quit Generated private data +> Done.`

**Comment by Waztom** [comment]
> /code/media/NEW_DATA/Mpro/Mpro-x1478_0/Mpro-x1478_0_pandda.map

@reskyner are these panda.map/ccp4/json type files not being picked up by the loader as they were not uploaded/missing as part of the Mpro data set?

**Comment by Waztom** [comment]
@tibor-postek-m2ms can you please try the data in this link: https://fragalysis-m2ms.slack.com/files/U011Z9BTP3N/F0151Q5L6BX/example.zip 

The loader works on my side using this data

**Comment by tibor-postek-m2ms** [comment]
I'm going to try it....thanks :)

**Comment by teriraj** [comment]
Selected tab: There are no values in score´s boxes

![2020-06-19_13h55_00](https://user-images.githubusercontent.com/65952633/85130049-7b021900-b234-11ea-9ee6-1dd11adf4bbc.png)

![2020-06-19_13h55_21](https://user-images.githubusercontent.com/65952633/85130075-86554480-b234-11ea-8c75-c7391e3593bf.png)


https://www.loom.com/share/23ab672c0dd54a97ab5ef2019c3f4251
